//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.WMCModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ComplaintMaster
    {
        public int pkid { get; set; }
        public string User_fkid { get; set; }
        public Nullable<int> Category_fkid { get; set; }
        public string ComplaintName { get; set; }
        public string ComplaintDescription { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> Active { get; set; }
        public string Longitutde { get; set; }
        public string Latitude { get; set; }
        public Nullable<int> City_fkid { get; set; }
        public string ShowIdentity { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Lid { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
    }
}
