//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.WMCModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MultipleFileUpload
    {
        public int pkid { get; set; }
        public Nullable<int> Master_fkid { get; set; }
        public Nullable<int> SubMaster_fkid { get; set; }
        public string filepath { get; set; }
        public Nullable<System.DateTime> Lastmodifieddatetime { get; set; }
        public Nullable<int> Lid { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
    }
}
