//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.WMCModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NewsAndUpdated
    {
        public int pkid { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ProfilePic { get; set; }
        public Nullable<System.DateTime> Addate { get; set; }
        public Nullable<System.DateTime> lastModified { get; set; }
        public Nullable<int> status { get; set; }
    }
}
