//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.WMCModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NoticeBoardMaster
    {
        public int pkid { get; set; }
        public string NoticeName { get; set; }
        public string NoticeDescription { get; set; }
        public string Image_Path { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> RequiredDays { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> City_fkid { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> Lid { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
    }
}
