//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.WMCModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WMC_WebApplicationEntities : DbContext
    {
        public WMC_WebApplicationEntities()
            : base("name=WMC_WebApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Category_Complaint> tbl_Category_Complaint { get; set; }
        public virtual DbSet<tbl_CityMaster> tbl_CityMaster { get; set; }
        public virtual DbSet<tbl_ComplaintMaster> tbl_ComplaintMaster { get; set; }
        public virtual DbSet<tbl_CountryMaster> tbl_CountryMaster { get; set; }
        public virtual DbSet<tbl_DeletedNoticeUser> tbl_DeletedNoticeUser { get; set; }
        public virtual DbSet<tbl_Emergency_ContactUs> tbl_Emergency_ContactUs { get; set; }
        public virtual DbSet<tbl_EmergencyContactCategory> tbl_EmergencyContactCategory { get; set; }
        public virtual DbSet<tbl_feedback_Master> tbl_feedback_Master { get; set; }
        public virtual DbSet<tbl_LikesMaster> tbl_LikesMaster { get; set; }
        public virtual DbSet<tbl_MultipleFileUpload> tbl_MultipleFileUpload { get; set; }
        public virtual DbSet<tbl_NewsAndUpdated> tbl_NewsAndUpdated { get; set; }
        public virtual DbSet<tbl_NoticeBoardMaster> tbl_NoticeBoardMaster { get; set; }
        public virtual DbSet<tbl_Prabhag_Master> tbl_Prabhag_Master { get; set; }
        public virtual DbSet<tbl_StateMaster> tbl_StateMaster { get; set; }
        public virtual DbSet<tbl_suggestionMaster> tbl_suggestionMaster { get; set; }
        public virtual DbSet<tbl_Tourism_Category> tbl_Tourism_Category { get; set; }
        public virtual DbSet<tbl_Tourism_SubCategory> tbl_Tourism_SubCategory { get; set; }
        public virtual DbSet<tbl_TourismMaster> tbl_TourismMaster { get; set; }
        public virtual DbSet<tbl_UserDetails> tbl_UserDetails { get; set; }
        public virtual DbSet<tbl_Ward_master> tbl_Ward_master { get; set; }
        public virtual DbSet<tbl_wardMember_Master> tbl_wardMember_Master { get; set; }
    }
}
